CREATE TABLE IF NOT EXISTS cidades (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estado_id INT UNSIGNED NOT NULL,
    area DECIMAL(20,2),
    UNIQUE KEY (nome),
    FOREIGN KEY (estado_id) REFERENCES estados (id)
);